.macro macro_setup
	LDI R16, HIGH(RAMEND)
	OUT SPH, R16
	LDI R16, LOW(RAMEND)
	OUT SPL, R16

	LDI	R16,0xFF
	OUT	DDRD,R16	;	SET ALL PORTD PINS AS OUTPUT
	SBI	PORTD,2		;	PULL UP PORTD2
	CBI DDRD,2		;	SET D2 PIN OF PORTD2 AS INPUT
	SBI	DDRC,DDC0	;	SET C0 PIN OF PORTC AS OUTPUT
	SBI	DDRC,DDC1	;	SET C1 PIN OF PORTC AS OUTPUT
	SBI	DDRC,DDC2	;	SET C2 PIN OF PORTC AS OUTPUT
	SBI	DDRB,DDB0	;	SET B0 PIN OF PORTB AS OUTPUT
	SBI	DDRB,DDB1	;	SET B1 PIN OF PORTB AS OUTPUT
	CBI	DDRB,DDB2	;	SET B2 PIN OF PORTB AS INPUT
.endmacro

.macro macro_display
	CLI
	IN	R26,SREG
	MOV		R1,	@0
	MOV		R2,	@1
	RCALL	CONV_DEC
	RCALL	DISPLAY		
	OUT		SREG,	R26
.endmacro

.macro macro_timer0
    LDI R16, (1<<CS00)|(1<<CS01)
    OUT TCCR0, R16
    LDI R16, (1<<TOIE0)
    OUT TIMSK, R16
.endmacro

.macro macro_int0
	LDI R16,(0<<ISC00)|(1<<ISC01)	;FALLING EDGE
	OUT MCUCR, R16

	LDI	R16,(1<<INT0)
	OUT	GICR,R16		;ENABLE INT0 EXTERNAL INTERRUPT	
.endmacro

.macro macro_adc
	ldi r16, 0x00 
	out ADMUX, r16 ;RESET ADMUX
	sbi ADMUX, REFS0 ;REFS0 AND REFS1 SET FOR VREF SELECTION
	sbi ADMUX, REFS1 ;VREF=INTERNAL 2.56V
	sbi ADMUX, MUX0 ;MUX0 SET AND MUX1 SET 
	sbi ADMUX, MUX1 ;ACTIVE CHANNEL IS ADC3 
	ldi r16, 0x00 

	out ADCSRA, r16 ;RESET ADCSRA 
	sbi ADCSRA, ADPS0 ;PRESCALER ADJUSTMENT
	cbi ADCSRA, ADPS1 ;ADPS0 set, ADPS1 and ADPS2 cleared
	cbi ADCSRA, ADPS2 ;PRESCLAER = CLK/16
	sbi ADCSRA, ADEN ;ADC ENABLED 
	sbi ADCSRA,ADIE ;ADC INTERRUPT ENABLED
.endmacro

